name: CRAWFORD
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - ca-certificates=2022.12.7
  - cairo=1.16.0
  - fontconfig=2.14.1
  - freetype=2.12.1
  - gdk-pixbuf=2.42.10
  - glib=2.69.1
  - icu=58.2
  - jbig=2.1
  - jpeg=9e
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libdeflate=1.8
  - libffi=3.4.2
  - libgcc-ng=12.2.0
  - libpng=1.6.39
  - libstdcxx-ng=11.2.0
  - libtiff=4.3.0
  - libuuid=2.38.1
  - libwebp-base=1.3.0
  - libxcb=1.13
  - libxml2=2.9.14
  - libzlib=1.2.13
  - llvm-openmp=16.0.0
  - lz4-c=1.9.3
  - ncurses=6.4
  - openjpeg=2.5.0
  - openslide=3.4.1
  - openssl=1.1.1t
  - pcre=8.45
  - pip=23.0.1
  - pixman=0.38.0
  - pthread-stubs=0.4
  - python=3.9.16
  - readline=8.2
  - sqlite=3.41.1
  - tk=8.6.12
  - tzdata=2022g
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.8.4
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.10
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
      - absl-py==1.0.0
      - accelerate==0.10.0
      - aiohttp==3.8.4
      - aiosignal==1.3.1
      - antlr4-python3-runtime==4.9.3
      - argcomplete==2.0.0
      - argon2-cffi==21.1.0
      - astor==0.8.1
      - astunparse==1.6.3
      - async-timeout==4.0.2
      - attrs==21.2.0
      - autograd==1.3
      - autograd-gamma==0.5.0
      - backcall==0.2.0
      - beartype==0.12.0
      - bitsandbytes-cuda111==0.26.0.post2
      - bleach==4.1.0
      - cachetools==4.2.4
      - certifi==2021.10.8
      - cffi==1.15.0
      - charset-normalizer==2.0.7
      - click==8.1.8
      - debugpy==1.5.1
      - decorator==5.1.0
      - deepspeed==0.6.5
      - defusedxml==0.7.1
      - diffusers==0.2.4
      - distlib==0.3.4
      - docker-pycreds==0.4.0
      - docopt==0.6.2
      - einops==0.6.0
      - einops-exts==0.0.3
      - ema-pytorch==0.2.1
      - entrypoints==0.3
      - filelock==3.6.0
      - flatbuffers==1.12
      - fonttools==4.28.2
      - formulaic==0.3.2
      - frozenlist==1.3.3
      - fsspec==2023.3.0
      - future==0.18.2
      - gast==0.4.0
      - gitdb==4.0.9
      - gitpython==3.1.27
      - google-auth==2.3.3
      - google-auth-oauthlib==0.4.6
      - google-pasta==0.2.0
      - grad-cam==1.3.7
      - grpcio==1.42.0
      - h5py==3.7.0
      - hjson==3.0.2
      - huggingface-hub==0.8.1
      - hydra-core==1.3.2
      - idna==3.3
      - imageio==2.14.1
      - imbalanced-learn==0.9.0
      - imgaug==0.4.0
      - importlib-metadata==4.8.2
      - interface-meta==1.2.4
      - ipykernel==6.5.1
      - ipython==7.29.0
      - ipython-genutils==0.2.0
      - ipywidgets==7.6.5
      - jedi==0.18.1
      - jinja2==3.0.3
      - joblib==1.1.0
      - jpeg4py==0.1.4
      - jsonschema==4.2.1
      - jupyter==1.0.0
      - jupyter-client==7.1.0
      - jupyter-console==6.4.0
      - jupyter-core==4.9.1
      - jupyterlab-pygments==0.1.2
      - jupyterlab-widgets==1.0.2
      - kaggle==1.5.12
      - keras==2.9.0
      - keras-preprocessing==1.1.2
      - kiwisolver==1.3.2
      - kornia==0.6.4
      - libclang==14.0.6
      - lifelines==0.27.0
      - lightly==1.3.1
      - lightly-utils==0.0.2
      - lightning-utilities==0.8.0
      - llvmlite==0.37.0
      - lmdb==1.3.0
      - markdown==3.3.6
      - markupsafe==2.0.1
      - matplotlib==3.5.0
      - matplotlib-inline==0.1.3
      - mistune==0.8.4
      - multidict==6.0.4
      - nbclient==0.5.9
      - nbconvert==6.3.0
      - nbformat==5.1.3
      - nest-asyncio==1.5.1
      - networkx==2.6.3
      - ninja==1.10.2.3
      - nonechucks==0.4.2
      - notebook==6.4.6
      - numba==0.54.1
      - numpy==1.20.3
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - oauthlib==3.1.1
      - omegaconf==2.3.0
      - opencv-python==4.5.4.58
      - openslide-python==1.1.2
      - opt-einsum==3.3.0
      - packaging==21.3
      - pandas==1.3.4
      - pandocfilters==1.5.0
      - parso==0.8.2
      - pathtools==0.1.2
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pillow==9.0.0
      - pipx==1.1.0
      - platformdirs==2.5.2
      - prometheus-client==0.12.0
      - promise==2.3
      - prompt-toolkit==3.0.22
      - protobuf==3.19.0
      - psutil==5.9.1
      - ptyprocess==0.7.0
      - py-cpuinfo==8.0.0
      - py-lz4framed==0.14.0
      - pyarrow==6.0.1
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pygments==2.10.0
      - pylibjpeg-libjpeg==1.2.0
      - pynndescent==0.5.5
      - pyparsing==3.0.6
      - pyro-api==0.1.2
      - pyrsistent==0.18.0
      - python-slugify==5.0.2
      - pytorch-fid==0.3.0
      - pytorch-lightning==1.9.4
      - pytorch-ranger==0.1.1
      - pytorch-warmup==0.1.0
      - pytz==2021.3
      - pyvips==2.1.16
      - pywavelets==1.2.0
      - pyyaml==6.0.2
      - pyzmq==22.3.0
      - qtconsole==5.2.1
      - qtpy==1.11.2
      - regex==2022.7.9
      - requests==2.26.0
      - requests-oauthlib==1.3.0
      - resize-right==0.0.2
      - rsa==4.8
      - scikit-image==0.19.1
      - scikit-learn==1.0.1
      - scipy==1.7.1
      - seaborn==0.11.2
      - send2trash==1.8.0
      - sentry-sdk==1.5.12
      - setproctitle==1.2.3
      - setuptools==59.5.0
      - setuptools-scm==6.3.2
      - shapely==1.8.4
      - shortuuid==1.0.9
      - six==1.16.0
      - smmap==5.0.0
      - spacecutter==0.2.0
      - tensorboard==2.9.1
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.0
      - tensorboardx==2.4
      - tensorflow==2.9.2
      - tensorflow-estimator==2.9.0
      - tensorflow-io-gcs-filesystem==0.26.0
      - termcolor==1.1.0
      - terminado==0.12.1
      - testpath==0.5.0
      - text-unidecode==1.3
      - theano==1.0.5
      - threadpoolctl==3.0.0
      - tifffile==2021.11.2
      - tokenizers==0.12.1
      - tomli==1.2.2
      - torch==1.10.1
      - torch-optimizer==0.3.0
      - torch-tb-profiler==0.3.1
      - torchgan==0.1.0
      - torchmetrics==0.11.4
      - torchvision==0.11.2
      - tornado==6.1
      - tqdm==4.62.3
      - traitlets==5.1.1
      - transformers==4.20.1
      - ttach==0.0.3
      - typing-extensions==4.5.0
      - umap-learn==0.5.2
      - urllib3==1.26.7
      - userpath==1.8.0
      - virtualenv==20.14.1
      - wandb==0.12.18
      - warmup-scheduler==0.3
      - wcwidth==0.2.5
      - webencodings==0.5.1
      - werkzeug==2.0.2
      - wget==3.2
      - wheel==0.37.1
      - widgetsnbextension==3.5.2
      - wrapt==1.14.0
      - yarl==1.8.2
      - zipp==3.6.0
